[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"


[tool.setuptools]
packages = ["dect"]

[project]
name = "dect"
version = "0.0.0"
dependencies = [
    "torch-scatter",
    "torch",
    "geotorch"
]

requires-python = ">=3.10"
authors = [
  {name = "Ernst Röell", email = "ernst.roeell@helmholtz-munich.de"},
  {name = "Bastian Rieck", email = "bastian.rieck@helmholtz-munich.de"},
]
maintainers = [
  {name = "Ernst Röell", email = "ernst.roeell@helmholtz-munich.de"},
]
description = "A fast package to compute the Euler Characteristic Transform"
readme = "README.md"
license = {file = "LICENSE.md"}
keywords = ["euler", "characteristic", "topology", "tda", "transform"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]
